### ISSUE TITLE
Can't build native image

### ISSUE THREAD

**Issue by mageddo** [dsyer/spring-boot-micro-apps#3]
I followed the steps described on the README but I didn't get success on the compilation process, looks like compiler is not founding some dependencies
[output.log](https://github.com/dsyer/spring-boot-micro-apps/files/2673865/output.log)

**Comment by kambleaa007** [comment]
have you tried on gitpod, it should work

**Comment by dsyer** [comment]
Those steps are old. I would recommend using the spring-native tooling. You also could use the Spring Boot maven plugin to build a container image with a native executable, but that won't work with the thin launcher (which is mainly used here for flexibility in testing, not really to do with runtime execution), so you probably want to change that too. I will get it working and put it on a branch somewhere when I get time.

**Comment by dsyer** [comment]
I added a "native" branch with configuration and instructions in the README.
