### ISSUE TITLE
Missing blocking example

### ISSUE THREAD

**Issue by jabrena** [dsyer/spring-boot-micro-apps#5]
Hi @dsyer, 

I was reviewing the whole project and I noticed that the examples put focus on Reactive stack but maybe a Blocking example could be interesting to add.

What do you think?

Juan Antonio

**Comment by dsyer** [comment]
The main objective was to be as light and as fast on start up as possible, so bringing a servlet container in is likely to be counterproductive, but if you have something concrete in mind that achieves the main objective I’m happy to look at it. Maybe it could go on a branch.

**Comment by jabrena** [comment]
Hi,

From my side, I like the repo because it explain how to use:
https://github.com/spring-projects-experimental/spring-boot-thin-launcher

```xml
<dependency>
    <groupId>org.springframework.boot.experimental</groupId>
    <artifactId>spring-boot-thin-layout</artifactId>
    <version>1.0.30.RELEASE</version>
</dependency>
```

But another outcome from this repository is the learning lesson about the different ways to use `Spring framework` without `Spring Boot`. 

Said that, if you observe, several examples here explore the Reactive stack:
https://github.com/dsyer/spring-boot-micro-apps/tree/main/src/main/java/com/example

but with Loom, Servlet stack take new relevance so, it could be nice to have a Servlet oriented example for:

- https://github.com/dsyer/spring-boot-micro-apps/blob/main/src/main/java/com/example/micro/MicroApplication.java
- https://github.com/dsyer/spring-boot-micro-apps/blob/main/src/main/java/com/example/func/FuncApplication.java

Do you see the value for the community?

**Comment by making** [comment]
If you are looking for an example for MVC.fn without Spring Boot, I have a simple one
https://github.com/making/vanilla-mvcfn

**Comment by jabrena** [comment]
Hi @making, 

many thanks for the example, it helped me.
https://github.com/jabrena/servlet-archaeology/blob/main/2-spring-framework/src/main/java/info/jab/ms/mvcfn/Main.java

I will try to understand more  and more the example but for a Servlet context:

- https://github.com/dsyer/spring-boot-micro-apps/blob/main/src/main/java/com/example/func/FuncApplication.java

Cheers
